name: GitHub Pages Deployment


on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout Deployment
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run build

      - name: Deployment 
        uses: JamesIves/github-pages-deploy-actions@4.2.5
        with: 
          branch: gh-pages
          folder: build
             